   FROM registry.svc.ci.openshift.org/origin/4.6@sha256:ebed81a9f96be3b84fdfb231c48020afd844d7a236a4552c9a2e33b121bc9a47 AS artifacts
  FROM registry.svc.ci.openshift.org/origin/4.6@sha256:9431e13df1bb280512afee2db730d353944b724a10fb967b78a26de4dddddfec AS machine_config_operator_rpms

  FROM quay.io/coreos-assembler/coreos-assembler:latest AS build
  USER 0
  COPY --from=artifacts /srv/repo/*.rpm /tmp/rpms/
  COPY --from=machine_config_operator_rpms /srv/repo/*.rpm /tmp/rpms/
  RUN set -exuo pipefail && \
      EXTENSION_RPMS=(           \
        attr                     \
        glusterfs                \
        glusterfs-client-xlators \
        glusterfs-fuse           \
        glusterfs-libs           \
        psmisc                   \
        NetworkManager-ovs       \
        openvswitch              \
        dpdk                     \
        gdbm-libs                \
        libxcrypt-compat         \
        unbound-libs             \
        python3-libs             \
        hwdata                   \
        libdrm                   \
        libmspack                \
        libpciaccess             \
        pciutils                 \
        pciutils-libs            \
        python-pip-wheel         \
        python-setuptools-wheel  \
        python3                  \
        python3-libs             \
        open-vm-tools            \
        xmlsec1                  \
        xmlsec1-openssl          \
        libxslt                  \
        libtool-ltdl             \
      )                       && \
      CRIO_RPMS=(                \
        cri-o                    \
        cri-tools                \
      )                       && \
      CRIO_VERSION="1.18"     && \
      curl -L "https://builds.coreos.fedoraproject.org/prod/streams/next-devel/builds/32.20200904.10.0/x86_64/fedora-coreos-32.20200904.10.0-ostree.x86_64.tar" | tar xf - -C /srv/repo/ --no-same-owner && \
      rm -rf /etc/yum.repos.d && \
      ostree --repo=/srv/repo checkout "fedora/x86_64/coreos/next-devel" --subpath /usr/etc/yum.repos.d --user-mode /etc/yum.repos.d && \
      dnf clean all && \
      mkdir -p /extensions/okd && \
      yumdownloader --archlist=x86_64 --disablerepo='*' --destdir=/extensions/okd --enablerepo=fedora --enablerepo=updates --enablerepo=updates-testing ${EXTENSION_RPMS[*]} && \
      createrepo_c --no-database /extensions && \
      mkdir /tmp/working && \
      pushd /tmp/working && \
        sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/fedora-updates-testing-modular.repo && \
        dnf module enable -y cri-o:${CRIO_VERSION} && \
        yumdownloader --archlist=x86_64 --disablerepo='*' --destdir=/tmp/rpms --enablerepo=updates-testing-modular ${CRIO_RPMS[*]} && \
        for i in $(find /tmp/rpms/ -iname *.rpm); do echo "Extracting $i ..."; rpm2cpio $i | cpio -div; done && \
        rm -rf etc/localtime && \
        ln -s ../usr/share/zoneinfo/UTC etc/localtime && \
        mv etc usr/ && \
      popd && \
      mkdir -p /tmp/working/usr/bin && \
      cp -rvf /srv/addons/* /tmp/working/ && \
      rm -rf /tmp/working/etc/yum.repos.d && \
      coreos-assembler dev-overlay --repo /srv/repo --rev "fedora/x86_64/coreos/next-devel" --add-tree /tmp/working --output-ref "fedora/x86_64/coreos/next-devel"

  FROM scratch
  COPY --from=build /srv/ /srv/
  COPY --from=build /extensions/ /extensions/
  LABEL version=32.20200904.10.0 \
        id-artifacts=sha256:ebed81a9f96be3b84fdfb231c48020afd844d7a236a4552c9a2e33b121bc9a47 \
        id-machine-config-operator-rpms=sha256:9431e13df1bb280512afee2db730d353944b724a10fb967b78a26de4dddddfec \
        "io.openshift.build.versions=machine-os=32.20200904.10" \
        "io.openshift.build.version-display-names=machine-os=Fedora CoreOS"
  ENTRYPOINT ["/noentry"] 
