apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: master-extensions
spec:
  config:
    ignition:
      version: 3.1.0
  extensions:
    - glusterfs
    - glusterfs-fuse
    - open-vm-tools
    - NetworkManager-ovs
